= FreeIPA

Deploy a FreeIPA cluster using Ansible.

== Requirements

- Libvirt 5.6.0+
- Terraform 0.12.25+
- Libvirt provider for Terraform 0.6.2+
- Ansible 2.9.9+
- OpenSSL 1.1.1+
- Linux password manager 1.7.3+

Install requirements.

[source,bash]
----
make requirements
----

== Setup Libvirt

Use `+virsh+` command utility to configure libvirt.

[source,bash]
----
export LIBVIRT_DEFAULT_URI="qemu:///system"
----

Check if libvirt is running.

[source,bash]
----
virsh version --daemon
----

=== QEMU permissions

The provider does not currently support to create volumes with different mode than `+root:root+` so QEMU agent must run as priviledged. Set user and password in `+/etc/libvirt/qemu.conf+` file.

[source,bash]
----
sed -i '/^#user/s/^#//' /etc/libvirt/qemu.conf
sed -i '/^#group/s/^#//' /etc/libvirt/qemu.conf
----

Restart libvirt daemon.

[source,bash]
----
systemctl restart libvirtd
----

== Deploy infrastructure

Deploy infrastructure using Terraform.

[source,bash]
----
make
----

== Deploy FreeIPA cluster

Clone upstream project.

[source,bash]
----
git clone https://github.com/freeipa/ansible-freeipa.git ansible/ansible-freeipa
----

Deploy FreeIPA server.

[source,bash]
----
ansible-playbook ansible/playbooks/install-server.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/server.yml"
----

Deploy FreeIPA replicas.

[source,bash]
----
ansible-playbook ansible/playbooks/install-replica.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/replica.yml"
----

Enroll FreeIPA clients.

[source,bash]
----
ansible-playbook ansible/playbooks/install-client.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml"
----

== Day-2 operations

Create FreeIPA groups.

[source,bash]
----
ansible-playbook ansible/playbooks/provision-groups.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/groups.yml"
----

Create FreeIPA users.

[source,bash]
----
ansible-playbook ansible/playbooks/provision-users.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "ipa_users_folder=variables/localhost/users" \
    --extra-vars "ipa_user_id=*"
----

Create only one FreeIPA user.

[source,bash]
----
ansible-playbook ansible/playbooks/provision-users.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "ipa_users_folder=variables/localhost/users" \
    --extra-vars "ipa_user_id=alice"
----

== Troubleshooting

=== Terraform

Enable debug mode by setting `+TF_VAR_DEBUG+` to `+true+` before planning terraform changes.

[source,bash]
----
export TF_VAR_DEBUG="true"
----

=== FreeIPA

Get FreeIPA password for `+admin+` user.

[source,bash]
----
pass freeipa/localhost/ipaadmin/password
----

Get Directory server with administration capabilities.

[source,bash]
----
pass freeipa/localhost/ipadm/password
----

== References

- https://github.com/freeipa/freeipa
- https://github.com/freeipa/ansible-freeipa