= FreeIPA

Deploy a FreeIPA cluster using Ansible.

== Requirements

- Libvirt 5.6.0+
- Terraform 0.12.25+
- Libvirt provider for Terraform 0.6.2+
- Ansible 2.9.9+
- OpenSSL 1.1.1+
- Linux password manager 1.7.3+

Install requirements.

[source,bash]
----
make requirements
----

== Setup Libvirt

Use `+virsh+` command utility to configure libvirt.

[source,bash]
----
export LIBVIRT_DEFAULT_URI="qemu:///system"
----

Check if libvirt is running.

[source,bash]
----
virsh version --daemon
----

=== QEMU permissions

The provider does not currently support to create volumes with different mode than `+root:root+` so QEMU agent must run as priviledged. Set user and password in `+/etc/libvirt/qemu.conf+` file.

[source,bash]
----
sed -i '/^#user/s/^#//' /etc/libvirt/qemu.conf
sed -i '/^#group/s/^#//' /etc/libvirt/qemu.conf
----

Restart libvirt daemon.

[source,bash]
----
systemctl restart libvirtd
----

== Deploy infrastructure

Deploy infrastructure using Terraform.

[source,bash]
----
make
----

== Deploy FreeIPA cluster

Clone upstream project.

[source,bash]
----
git clone https://github.com/freeipa/ansible-freeipa.git ansible/ansible-freeipa
----

=== First server

Deploy FreeIPA first server.

[source,bash]
----
ansible-playbook ansible/playbooks/install-server.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/server.yml"
----

=== Replicas

Deploy FreeIPA replicas.

[source,bash]
----
ansible-playbook ansible/playbooks/install-replica.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/replica.yml"
----

=== Topology

Modify FreeIPA topology.

[source,bash]
----
ansible-playbook ansible/playbooks/configure-topology.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/topology-segments.yml"
----

=== Default configuration

Modify default FreeIPA configuration.

[source,bash]
----
ansible-playbook ansible/playbooks/configure-default-settings.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/default-configuration.yml"
----

== Users management

Provision (create, modify and delete) groups and users.

=== Groups

Create FreeIPA groups.

[source,bash]
----
ansible-playbook ansible/playbooks/provision-groups.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/groups.yml"
----

=== Password policy

Set password policy for FreeIPA groups.

[source,bash]
----
ansible-playbook ansible/playbooks/configure-pwpolicy.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/password-policies.yml"
----

=== Users

Create FreeIPA users.

[source,bash]
----
ansible-playbook ansible/playbooks/provision-users.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "ipa_users_folder=variables/localhost/users" \
    --extra-vars "ipa_user_id=*"
----

Create only one FreeIPA user.

[source,bash]
----
ansible-playbook ansible/playbooks/provision-users.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "ipa_users_folder=variables/localhost/users" \
    --extra-vars "ipa_user_id=alice"
----

=== MFA

Enable MFA for a user.

[source,bash]
----
ipa otptoken-add --owner=${user_id}
----

=== RBAC

Create FreeIPA service accounts.

[source,bash]
----
ansible-playbook ansible/playbooks/provision-users.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "ipa_users_folder=variables/localhost/sysaccounts" \
    --extra-vars "ipa_user_id=*"
----

== Hosts management

Provision (create, modify and delete) hosts as FreeIPA clients.

=== Host groups

Create FreeIPA host groups.

[source,bash]
----
ansible-playbook ansible/playbooks/provision-host-groups.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/host-groups.yml"
----

=== Enrollment

Enroll FreeIPA clients in two steps using Ansible.

[source,bash]
----
ansible-playbook ansible/playbooks/provision-hosts.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/hosts.yml"
----

Then, get into the host an run the following command (use the OTP from host-auth.log file).

[source,bash]
----
ipa-client-install -W
----

TIP: The enrollment process can be automated at startup using a link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/linux_domain_identity_authentication_and_policy_guide/client-kickstart[kickstart] or a link:https://www.freedesktop.org/software/systemd/man/systemd.service.html[systemd unit].

Or enroll FreeIPA clients in one step.

[source,bash]
----
ansible-playbook ansible/playbooks/install-client.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/hosts.yml"
----

=== HBAC

Manage HBAC rules.

[source,bash]
----
ansible-playbook ansible/playbooks/configure-hbac.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/hbac-rules.yml"
----

=== Sudo rules

Manage sudo rules.

[source,bash]
----
ansible-playbook ansible/playbooks/configure-sudo.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/sudo-rules.yml"
----

*IMPORTANT*: If sudo rules are weak, it is possible to escalate privileges:

[source,bash]
----
sudo vi -c '!bash'
----

== LDAP clients integration

Create LDAP bind accounts.

[source,bash]
----
ansible-playbook ansible/playbooks/provision-ldap-accounts.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "@ansible/variables/localhost/ldap-accounts.yml"
----

Find users in FreeIPA LDAP.

[source,bash]
----
ldapsearch -W -H ldap://ipaserver.test.local \
    -D "uid=bind-test,cn=sysaccounts,cn=etc,dc=test,dc=local" \
    -b "cn=users,cn=accounts,dc=test,dc=local" \
    -s one "(objectClass=inetorgperson)"
----

Find groups in FreeIPA LDAP.

[source,bash]
----
ldapsearch -W -H ldap://ipaserver.test.local \
    -D "uid=bind-test,cn=sysaccounts,cn=etc,dc=test,dc=local" \
    -b "cn=groups,cn=accounts,dc=test,dc=local" \
    -s one "(objectClass=posixgroup)"
----

== Disaster recovery

Backup and restore FreeIPA data.

=== Backup

Perform a full backup.

[source,bash]
----
ansible-playbook ansible/playbooks/backup-server.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "ipa_backup_type=full"
----

Perform a data-only backup.

[source,bash]
----
ansible-playbook ansible/playbooks/backup-server.yml \
    --inventory ansible/inventory/localhost.yml \
    --extra-vars "@ansible/variables/localhost/main.yml" \
    --extra-vars "ipa_backup_type=data-only"
----

=== Restore

Copy backup to FreeIPA server and restore using `+ipa-restore+` utility.

[source,bash]
----
ipa-restore ${IPA_BACKUP_PATH}
----

== Troubleshooting

=== Terraform

Enable debug mode by setting `+TF_VAR_DEBUG+` to `+true+` before planning terraform changes.

[source,bash]
----
export TF_VAR_DEBUG="true"
----

=== FreeIPA

Get FreeIPA password for `+admin+` user.

[source,bash]
----
pass freeipa/localhost/ipaadmin/password
----

Get Directory server with administration capabilities.

[source,bash]
----
pass freeipa/localhost/ipadm/password
----

== References

- https://github.com/freeipa/freeipa
- https://github.com/freeipa/ansible-freeipa
- https://blog.delouw.ch/2018/07/02/centrally-manage-selinux-user-mapping-with-freeipa
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/using_selinux/index
- https://www.freeipa.org/page/HowTo/LDAP
