ipaadmin_principal: hosts-provisioner
ipaadmin_password: "{{ lookup('passwordstore', 'freeipa/localhost/hosts-provisioner/password') }}"

ipa_hosts:
  - name: ipaserver.test.local
    groups:
      - ipaservers
      - iamservers
      - datacenter-core
    state: present

  - name: ipareplica00.test.local
    groups:
      - ipaservers
      - iamservers
      - datacenter-core
    state: present

  - name: ipareplica01.test.local
    groups:
      - ipaservers
      - iamservers
      - datacenter-core
    state: present

  - name: ipabastion.test.local
    groups:
      - bastions
      - datacenter-core
    state: present