# Domain configuration
ipaserver_domain: test.local
ipaserver_realm: TEST.LOCAL

# FreeIPA configuration
ipaadmin_principal: admin
ipaadmin_password:
  "{{ lookup('passwordstore', 'freeipa/localhost/ipaadmin/password create=true length=32 nosymbols=yes') }}"

# Directory server configuration
ipadm_password:
  "{{ lookup('passwordstore', 'freeipa/localhost/ipadm/password create=true length=32 nosymbols=yes') }}"

# NTP configuration
ipaclient_no_ntp: no

# Users database
ipa_users_folder: variables/localhost/users