name: bob
first: Bob
last: Example
sshpubkey:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/HQd/8zjZsuyHB3PZvPNTxhZVWh2Kp49XartYDD7DeOLG6HaZBWXS9A7NU2dEkFkIokaonArZM6ouFC9UUpeXcdBUxc3CIYYz4nXGEo3EST4VB/3AEe9/RVAkfQWRFYbVXwKiVu6DbP8yPlOLjJ1c74OD8GQk0NpDCR1ogu8Fob6kcqR518TPimo5ib5uLgSkbReAIynuNb9NDnDu976RX2+1LKd/VUncC6h0SUezHxGkp/hnAdwAVVo/HSk6RYFEjx41k8vERTU+DFKnSojoSpsGWO2aojzyqXl3qPSfnPuvT1GMW4Kz+dkxDrpNOYkabvmOX8N2E9Fms2uQQLDXjPzku0WZc8VqbWXV3e13CAgzZIWkAx28+N7WSl2td/RWBZUsY9HyhThGRX13x7Qn2RUMaK/YQXjxlfEjj1AbNZn4Ae8Xuf55EXKNILzQVtrFQEXAh0wpF4kIvUPDGzOqyQItK1rUoSE9L7Lzh6tjT//rw9zo3M/0EFMLMDX3ePqvk5hr/pyZXwB3Z7IBuztCt+kskQ0Ct6KvfacfGBGQmZlbwx9r9xSRkJlv6zKuflBnceDWIMj4lAbTvsYG6U2TWvFEQ+AWJ1/ZOrb7wdwr6ldFLLB5hV1g3e873Bwh/lFBLTNHZr7SAQ+NdzUEyIhfCVFxLzAzUbZp8QcCMtJB4w=="
groups:
  - sysadmins
email: bob@example.io
phone: "+34666444555"
employeetype: Analyst
employeenumber: 4096
departmentnumber: 1024
orgunit: SA
city: Winterfell
postalcode: 99999
preferredlanguage: es
state: present