---
- name: Playbook to manage FreeIPA topology segments
  hosts: ipaserver:ipareplicas
  become: true
  gather_facts: false
  run_once: true
  tasks:
    - name: Configure FreeIPA topology segment
      ipatopologysegment:
        ipaadmin_principal: "{{ ipaadmin_principal | default(omit) }}"
        ipaadmin_password: "{{ ipaadmin_password | mandatory }}"
        name: "{{ ipa_topology_segment.name | default(omit) }}"
        suffix: "{{ ipa_topology_segment.suffix | mandatory }}"
        left: "{{ ipa_topology_segment.left | mandatory }}"
        right: "{{ ipa_topology_segment.right | mandatory }}"
        state: "{{ ipa_topology_segment.state | default('present') }}"
      loop:
        "{{ ipa_topology_segments }}"
      loop_control:
        loop_var: ipa_topology_segment
