---
- name: Playbook to provision FreeIPA groups
  hosts: ipaserver:ipareplicas
  become: true
  gather_facts: false
  run_once: true
  tasks:
    - name: Provision FreeIPA groups
      vars:
        ipaadmin_principal: "{{ ipaadmin_principal | default(omit) }}"
        ipaadmin_password: "{{ ipaadmin_password | mandatory }}"
        ipa_group: "{{ ipa_group }}"
      include_role:
        name: ipagroup
      loop:
        "{{ ipa_groups }}"
      loop_control:
        loop_var: ipa_group
