---
- name: Playbook to provision FreeIPA hosts
  hosts: ipaserver:ipareplicas
  become: true
  gather_facts: false
  run_once: true
  tasks:
    - name: Provision FreeIPA hosts
      vars:
        ipaadmin_principal: "{{ ipaadmin_principal | default(omit) }}"
        ipaadmin_password: "{{ ipaadmin_password | mandatory }}"
        ipa_host: "{{ ipa_host }}"
      include_role:
        name: ipahost
      loop:
        "{{ ipa_hosts }}"
      loop_control:
        loop_var: ipa_host
