---
- name: Get information for the role {{ ipa_user_role }}
  ipa_role:
    ipa_host: localhost
    ipa_user: "{{ ipaadmin_principal | default(omit) }}"
    ipa_pass: "{{ ipaadmin_password | mandatory }}"
    validate_certs: no
    name: "{{ ipa_user_role }}"
  register: ipa_role_info

- name: Get users for the role {{ ipa_user_role }}
  set_fact:
    ipa_role_members: "{{ ipa_role_info.role.member_user | default([]) }}"

- name: Delete role {{ ipa_user_role }} from the user {{ ipa_user.name }}
  ipa_role:
    ipa_host: localhost
    ipa_user: "{{ ipaadmin_principal | default(omit) }}"
    ipa_pass: "{{ ipaadmin_password | mandatory }}"
    validate_certs: no
    name: "{{ ipa_user_role }}"
    user: "{{ ipa_role_members | difference([ ipa_user.name ]) }}"
  when:
    - ipa_user.name in ipa_role_members