---
- name: Get information for the group {{ ipa_user_group }}
  ipa_group:
    ipa_host: localhost
    ipa_user: "{{ ipaadmin_principal | default(omit) }}"
    ipa_pass: "{{ ipaadmin_password | mandatory }}"
    validate_certs: no
    name: "{{ ipa_user_group }}"
  register: ipa_group_info

- name: Get membership for the group {{ ipa_user_group }}
  set_fact:
    ipa_group_members: "{{ ipa_group_info.group.member_user | default([]) }}"
    ipa_group_indirect_members: "{{ ipa_group_info.group.memberindirect_user | default([]) }}"

- name: Delete user {{ ipa_user.name }} from the group {{ ipa_user_group }}
  ipa_group:
    ipa_host: localhost
    ipa_user: "{{ ipaadmin_principal | default(omit) }}"
    ipa_pass: "{{ ipaadmin_password | mandatory }}"
    validate_certs: no
    name: "{{ ipa_user_group }}"
    user: "{{ ipa_group_members | difference([ ipa_user.name ]) }}"
  when:
    - ipa_user.name in ipa_group_members
