---
- name: Send e-mail with credentials to user {{ ipa_user.name }}
  become: false
  delegate_to: localhost
  mail:
    host: "{{ smtp_server.host }}"
    port: "{{ smtp_server.port }}"
    username: "{{ smtp_server.user }}"
    password: "{{ smtp_server.pass }}"
    subject: You have been registered in FreeIPA
    body: "{{ lookup('template', 'new-user-email.html.j2') }}"
    from: noreply@{{ ipaserver_domain }} (noreply)
    to: "{{ ipa_user.email }}"
