---
- name: Generate password manager path for the user {{ ipa_user.name }}
  set_fact:
    ipa_user_password_manager_path: "{{ ipa_user_password_to_pass_path }}/{{ ipa_user.name }}/password"

- name: Save the password for the user {{ ipa_user.name }} in the path {{ ipa_user_password_manager_path }}
  debug:
    msg: "{{ lookup('passwordstore', \
      (ipa_user_password_manager_path + ' userpass=' + ipa_user_password + ' create=true overwrite=true')) }}"
  no_log: true