---
- name: Get information for the role {{ ipa_group_role }}
  ipa_role:
    ipa_host: localhost
    ipa_user: "{{ ipaadmin_principal | default(omit) }}"
    ipa_pass: "{{ ipaadmin_password | mandatory }}"
    validate_certs: no
    name: "{{ ipa_group_role }}"
  register: ipa_role_info

- name: Add role {{ ipa_group_role }} to the group {{ ipa_group.name }}
  ipa_role:
    ipa_host: localhost
    ipa_user: "{{ ipaadmin_principal | default(omit) }}"
    ipa_pass: "{{ ipaadmin_password | mandatory }}"
    validate_certs: no
    name: "{{ ipa_group_role }}"
    group: "{{ (ipa_role_info.role.member_group | default([])) + [ ipa_group.name ] }}"
