= ipahost

Create a new group and manage its membership and RBAC.

== Role Variables

A description of the settable variables for this role should go here, including any variables that are in defaults/main.yml, vars/main.yml, and any variables that can/should be set via parameters to the role. Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.) should be mentioned here as well.

[cols="1,1,1,4",align="center",options="header",]
|===
| *Name*                     | *Type* | *Mandatory* | *Description*
| ipaadmin_principal         | string | yes         | User to authenticate against FreeIPA
| ipaadmin_password          | string | yes         | Password to authenticate against FreeIPA
| ipa_group                  | dict   | yes         | Contains the new FreeIPA group information
| ipa_group.name             | string | yes         | FQDN for the new group
| ipa_group.description      | string | no          | A description of this role-group
| ipa_group.groups           | list   | no          | List of subgroups assign to this group
| ipa_group.roles            | list   | no          | List of roles assign to this group
|===

== Example Playbook

Example of how to use this role.

[source,yaml]
----
- name: Playbook to provision FreeIPA groups
  hosts: ipaserver:ipareplicas
  become: true
  gather_facts: false
  run_once: true
  tasks:
    - name: Provision FreeIPA groups
      vars:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        ipa_group: "{{ new_ipa_group }}"
      include_role:
        name: ipa_group
----
